#!/usr/bin/env python3
"""Embed runtime assets (the MathJax/TeX->SVG JS bundle) into C++ sources."""
import os, sys, textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS = os.path.join(ROOT, "assets/js/mathjax-tex-svg.js")
OUT_DIR = os.path.join(ROOT, "src/generated")

def raw_string_literal(path, delimiter):
    with open(path, "r", encoding="utf-8", errors="surrogateescape") as f:
        data = f.read()
    if ")" + delimiter + '"' in data:
        raise SystemExit("delimiter clash, choose another one")
    return data

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    delim = "MDTJS_BUNDLE"
    data = raw_string_literal(JS, delim)
    hdr = os.path.join(OUT_DIR, "assets_js.h")
    src = os.path.join(OUT_DIR, "assets_js.cpp")
    with open(hdr, "w") as f:
        f.write("""// generated by tools/build_assets.py - do not edit
#pragma once
#include <cstddef>
namespace mdt {
extern const char* kMathJaxBundle;
extern const size_t kMathJaxBundleLen;
}  // namespace mdt
""")
    with open(src, "w") as f:
        f.write("// generated by tools/build_assets.py - do not edit\n")
        f.write('#include "assets_js.h"\n\nnamespace mdt {\n')
        f.write('static const char kBundle[] = R"%s(\n' % delim)
        f.write(data)
        f.write('\n)%s";\n' % delim)
        f.write("const char* kMathJaxBundle = kBundle;\n")
        f.write("const size_t kMathJaxBundleLen = %d;\n" % len(data.encode("utf-8")))
        f.write("}  // namespace mdt\n")
    print("wrote %s (%d bytes of JS)" % (src, len(data)))

if __name__ == "__main__":
    main()
